// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package repository

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Friend struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	UserID    *uuid.UUID         `json:"user_id"`
	OutingID  uuid.UUID          `json:"outing_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type OrderItem struct {
	ID        uuid.UUID       `json:"id"`
	ReceiptID uuid.UUID       `json:"receipt_id"`
	Name      string          `json:"name"`
	Price     sql.NullFloat64 `json:"price"`
	Quantity  int32           `json:"quantity"`
}

type OtherFee struct {
	ID        uuid.UUID       `json:"id"`
	ReceiptID uuid.UUID       `json:"receipt_id"`
	Name      string          `json:"name"`
	Price     sql.NullFloat64 `json:"price"`
}

type Outing struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	UserID    uuid.UUID          `json:"user_id"`
}

type Receipt struct {
	ID                uuid.UUID       `json:"id"`
	ReceiptImageID    uuid.UUID       `json:"receipt_image_id"`
	Restaurant        string          `json:"restaurant"`
	Address           string          `json:"address"`
	Opened            time.Time       `json:"opened"`
	OrderNumber       string          `json:"order_number"`
	OrderType         string          `json:"order_type"`
	TableNumber       string          `json:"table_number"`
	Server            string          `json:"server"`
	Subtotal          sql.NullFloat64 `json:"subtotal"`
	SalesTax          sql.NullFloat64 `json:"sales_tax"`
	Total             sql.NullFloat64 `json:"total"`
	PaymentMethod     string          `json:"payment_method"`
	PaymentAmountPaid sql.NullFloat64 `json:"payment_amount_paid"`
	PaymentTip        sql.NullFloat64 `json:"payment_tip"`
	Copy              string          `json:"copy"`
	CreatedAt         time.Time       `json:"created_at"`
}

type ReceiptImage struct {
	ID       uuid.UUID `json:"id"`
	Bucket   string    `json:"bucket"`
	Key      string    `json:"key"`
	RawText  string    `json:"raw_text"`
	FileName string    `json:"file_name"`
	Hash     string    `json:"hash"`
	OutingID uuid.UUID `json:"outing_id"`
}

type Split struct {
	ID          uuid.UUID          `json:"id"`
	FriendID    uuid.UUID          `json:"friend_id"`
	OrderItemID uuid.UUID          `json:"order_item_id"`
	ReceiptID   uuid.UUID          `json:"receipt_id"`
	Quantity    int32              `json:"quantity"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID            uuid.UUID          `json:"id"`
	Sub           string             `json:"sub"`
	Email         string             `json:"email"`
	Picture       string             `json:"picture"`
	EmailVerified bool               `json:"email_verified"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
